##################################################################################################
# MQTT client services
##################################################################################################
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{  .Chart.Name }}
#   labels:
#     app.kubernetes.io/managed-by: helm
#     meta.helm.sh/release-name: {{  .Chart.Name }}
#     meta.helm.sh/release-namespace: default
#     app: {{  .Chart.Name }}
#     service: {{  .Chart.Name }}
# spec:
#   selector:
#     app: {{  .Chart.Name }}
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{  .Chart.Name }}
#   labels:
#     app.kubernetes.io/managed-by: helm
#     meta.helm.sh/release-name: {{  .Chart.Name }}
#     meta.helm.sh/release-namespace: default
#     account: {{  .Chart.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Chart.Name }}-{{  .Values.mqttclient.version }}
  labels:
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: {{  .Chart.Name }}
    meta.helm.sh/release-namespace: default
    app: {{  .Chart.Name }}
    version: {{  .Values.mqttclient.version }}
spec:
  replicas: {{  .Values.mqttclient.replicaCount }}
  selector:
    matchLabels:
      app: {{  .Chart.Name }}
      version: {{  .Values.mqttclient.version }}
  template:
    metadata:
      labels:
        app: {{  .Chart.Name }}
        version: {{  .Values.mqttclient.version }}
    spec:
      serviceAccountName: {{  .Chart.Name }}
      containers:
      - name: {{  .Chart.Name }}
        image: {{ .Values.mqttclient.image.repository }}:{{ .Values.mqttclient.image.tag }}
        imagePullPolicy: {{ .Values.mqttclient.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mqttclient.service.servicePort}}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      imagePullSecrets:
        - name: {{ .Values.imagepullsecrets.name}}
      volumes:
      - name: tmp
        emptyDir: {}
---