##################################################################################################
# MQTT client services
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Chart.Name }}-{{  .Values.mqttclient.version }}
  namespace: {{ .Values.mqttclient.namespace }}
  labels:
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: {{  .Chart.Name }}
    meta.helm.sh/release-namespace: {{ .Values.mqttclient.namespace }}
    app: {{  .Chart.Name }}
    version: {{  .Values.mqttclient.version }}
spec:
  replicas: {{  .Values.mqttclient.replicaCount }}
  selector:
    matchLabels:
      app: {{  .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{  .Chart.Name }}
    spec:
      containers:
      - name: {{  .Chart.Name }}
        image: {{ .Values.mqttclient.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mqttclient.service.servicePort}}
---